### PR TITLE
Web project for displaying order queue length

### PR DESCRIPTION
**Pull request by jakobehn**

### CODE REVIEW

**Comment by jakobehn** [comment]
Ignore PR

**Comment by tomkerkhove** [comment]
Ignoring but feel free to ping me when it's ready, sounds interesting.

**Comment by jakobehn** [comment]
Will do, I'm building a web UI to make demos around KEDA a bit more visual :-)

**Comment by tomkerkhove** [comment]
Awesome, thanks! Just FYI, we have a dashboard (which is now broken) but we'll restart the work on that, you might be interested in that as well - https://github.com/kedacore/dashboard

/cc @jeffhollan

**Pull request closed without merging**
